// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module HAdder (
A1,S0,A0,S1,A2,A3,A4,A5,S5,S4,S3,S2,VDD,GND );
input  A1;
output  S0;
input  A0;
output  S1;
input  A2;
input  A3;
input  A4;
input  A5;
output  S5;
output  S4;
output  S3;
output  S2;
input  VDD;
input  GND;
wire S5;
wire VDD;
wire net25;
wire A1;
wire net16;
wire S0;
wire A0;
wire S4;
wire S3;
wire A2;
wire net21;
wire A4;
wire A5;
wire GND;
wire S1;
wire A3;
wire S2;
wire net20;

NOT    
 I43  ( .Vdd( VDD ), .In( A0 ), .GND( GND ), .Out( S0 ) );

XORG    
 I56  ( .VDD( VDD ), .A( A4 ), .GND( GND ), .B( net21 ), .out( S4 ) );

XORG    
 I53  ( .VDD( VDD ), .A( A5 ), .GND( GND ), .B( net25 ), .out( S5 ) );

XORG    
 I50  ( .VDD( VDD ), .A( A3 ), .GND( GND ), .B( net20 ), .out( S3 ) );

XORG    
 I44  ( .VDD( VDD ), .A( A1 ), .GND( GND ), .B( A0 ), .out( S1 ) );

XORG    
 I55  ( .VDD( VDD ), .A( A2 ), .GND( GND ), .B( net16 ), .out( S2 ) );

AND    
 I49  ( .Vdd( VDD ), .A( A2 ), .GND( GND ), .B( net16 ), .Out( net20 ) );

AND    
 I51  ( .Vdd( VDD ), .A( A3 ), .GND( GND ), .B( net20 ), .Out( net21 ) );

AND    
 I45  ( .Vdd( VDD ), .A( A1 ), .GND( GND ), .B( A0 ), .Out( net16 ) );

AND    
 I52  ( .Vdd( VDD ), .A( A4 ), .GND( GND ), .B( net21 ), .Out( net25 ) );

endmodule

