// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module ABS (
In0,In1,In2,In3,In4,In5 );
input  In0;
input  In1;
input  In2;
input  In3;
input  In4;
input  In5;
wire In0;
wire In1;
wire In3;
wire net3;
wire net6;
wire net12;
wire net4;
wire net2;
wire net8;
wire net7;
wire In4;
wire net18;
wire net17;
wire net19;
wire net16;
wire In2;
wire net21;
wire net14;
wire net13;
wire net9;
wire net11;
wire net15;
wire In5;
wire net1;
wire net5;
wire net20;
wire net10;

\12to1MUX     
 I0  ( .B5( net21 ), .Out4( net8 ), .B1( net17 ), .Vdd( net3 ), .A1( net11 ), .A0( net10 ), .Out0( net4 ), .B0( net16 ), .Out1( net5 ), .Selector( net1 ), .A2( net12 ), .Out3( net7 ), .B4( net20 ), .B2( net18 ), .A5( net15 ), .A4( net14 ), .GND( net2 ), .B3( net19 ), .A3( net13 ), .Out5( net9 ), .Out2( net6 ) );

endmodule

