// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module HW4 (
);
wire \vdd! ;
wire \VDD! ;
wire \gnd! ;
wire net13;
wire net12;
wire net11;
wire net10;
wire net6;

FO4    
 I2  ( .VGOLD( \VDD!  ), .VDD( \vdd!  ), .Z( net10 ), .A( net11 ), .GND( \gnd!  ) );

FO4    
 I1  ( .VGOLD( \VDD!  ), .VDD( net13 ), .Z( net11 ), .A( net12 ), .GND( \gnd!  ) );

FO4    
 I0  ( .VGOLD( \VDD!  ), .VDD( \vdd!  ), .Z( net12 ), .A( net6 ), .GND( \gnd!  ) );

cap    
 C0  ( .PLUS( net10 ), .MINUS( \gnd!  ) );

vdc    
 V0  ( .PLUS( \vdd!  ), .MINUS( net13 ) );

vpulse    
 V1  ( .PLUS( net6 ), .MINUS( \gnd!  ) );

endmodule

