// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module \4AND  (
A,B,C,Vdd,GND,Out,D );
input  A;
input  B;
input  C;
input  Vdd;
input  GND;
output  Out;
input  D;
wire net17;
wire Vdd;
wire net16;
wire C;
wire net15;
wire A;
wire B;
wire net010;
wire GND;
wire D;
wire Out;

nmos1v    
 NM3  ( .S( GND ), .G( D ), .B( GND ), .D( net010 ) );

nmos1v    
 NM2  ( .S( net010 ), .G( C ), .B( GND ), .D( net15 ) );

nmos1v    
 NM1  ( .S( net15 ), .G( B ), .B( GND ), .D( net16 ) );

nmos1v    
 NM0  ( .S( net16 ), .G( A ), .B( GND ), .D( net17 ) );

pmos1v    
 PM3  ( .S( Vdd ), .G( D ), .B( Vdd ), .D( net17 ) );

pmos1v    
 PM2  ( .S( Vdd ), .G( C ), .B( Vdd ), .D( net17 ) );

pmos1v    
 PM1  ( .S( Vdd ), .G( B ), .B( Vdd ), .D( net17 ) );

pmos1v    
 PM0  ( .S( Vdd ), .G( A ), .B( Vdd ), .D( net17 ) );

NOT    
 I1  ( .Vdd( Vdd ), .In( net17 ), .GND( GND ), .Out( Out ) );

endmodule

