// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module FO4 (
VGOLD,VDD,A,GND,Z );
input  VGOLD;
input  VDD;
input  A;
input  GND;
input  Z;
wire VGOLD;
wire VDD;
wire net19;
wire Z;
wire A;
wire GND;
wire net22;
wire net20;

INVX1    
 I3  ( .VDD( VGOLD ), .Z( net22 ), .A( A ), .GND( GND ) );

INVX1    
 I2  ( .VDD( VDD ), .Z( Z ), .A( A ), .GND( GND ) );

INVX1    
 I1  ( .VDD( VGOLD ), .Z( net20 ), .A( A ), .GND( GND ) );

INVX1    
 I0  ( .VDD( VGOLD ), .Z( net19 ), .A( A ), .GND( GND ) );

cap    
 C2  ( .PLUS( net19 ), .MINUS( GND ) );

cap    
 C1  ( .PLUS( net20 ), .MINUS( GND ) );

cap    
 C0  ( .PLUS( net22 ), .MINUS( GND ) );

endmodule

