// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module COMP_mod1 (
Out,GND,Vdd,Carry,A,B );
output  Out;
input  GND;
input  Vdd;
output  Carry;
input  A;
input  B;
wire Vdd;
wire net15;
wire net11;
wire A;
wire GND;
wire B;
wire net5;
wire Out;
wire Carry;

NOT    
 I8  ( .Vdd( Vdd ), .In( A ), .GND( GND ), .Out( net15 ) );

NOT    
 I9  ( .Vdd( Vdd ), .In( B ), .GND( GND ), .Out( net11 ) );

NOR    
 I5  ( .Vdd( Vdd ), .A( net5 ), .GND( GND ), .B( Carry ), .Out( Out ) );

AND    
 I7  ( .Vdd( Vdd ), .A( A ), .GND( GND ), .B( net11 ), .Out( Carry ) );

AND    
 I6  ( .Vdd( Vdd ), .A( net15 ), .GND( GND ), .B( B ), .Out( net5 ) );

endmodule

