// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module Inv (
inp,out,VDD,GND );
input  inp;
output  out;
input  VDD;
input  GND;
wire VDD;
wire gnd;
wire inp;
wire out;

nmos1v    
 NM0  ( .S( gnd ), .G( inp ), .B( gnd ), .D( out ) );

pmos1v    
 PM0  ( .S( VDD ), .G( inp ), .B( VDD ), .D( out ) );

endmodule

