// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module AND (
A,B,Vdd,GND,Out );
input  A;
input  B;
input  Vdd;
input  GND;
output  Out;
wire Vdd;
wire A;
wire GND;
wire B;
wire net020;
wire Out;
wire net10;

nmos1v    
 NM1  ( .S( GND ), .G( B ), .B( GND ), .D( net020 ) );

nmos1v    
 NM0  ( .S( net020 ), .G( A ), .B( GND ), .D( net10 ) );

pmos1v    
 PM1  ( .S( Vdd ), .G( B ), .B( Vdd ), .D( net10 ) );

pmos1v    
 PM0  ( .S( Vdd ), .G( A ), .B( Vdd ), .D( net10 ) );

NOT    
 I0  ( .Vdd( Vdd ), .In( net10 ), .GND( GND ), .Out( Out ) );

endmodule

