// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module NAND2 (
VDD,A,B,GND,OUT );
input  VDD;
input  A;
input  B;
input  GND;
output  OUT;
wire VDD;
wire net12;
wire A;
wire OUT;
wire GND;
wire B;

pmos1v    
 PM1  ( .S( VDD ), .G( B ), .B( VDD ), .D( OUT ) );

pmos1v    
 PM0  ( .S( VDD ), .G( A ), .B( VDD ), .D( OUT ) );

nmos1v    
 NM1  ( .S( GND ), .G( B ), .B( GND ), .D( net12 ) );

nmos1v    
 NM0  ( .S( net12 ), .G( A ), .B( GND ), .D( OUT ) );

endmodule

