// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module \6bit_FA  (
A0,A1,A2,A3,A4,A5,B0,BH1,Cin,B4,B5,B6,B2,GND,VDD,S0,S1,S2,S3,S4,S5,nothing );
input  A0;
input  A1;
input  A2;
input  A3;
input  A4;
input  A5;
input  B0;
input  BH1;
input  Cin;
input  B4;
input  B5;
input  B6;
input  B2;
input  GND;
input  VDD;
output  S0;
output  S1;
output  S2;
output  S3;
output  S4;
output  S5;
output  nothing;
wire VDD;
wire net47;
wire A0;
wire S3;
wire S4;
wire GND;
wire A3;
wire S5;
wire B5;
wire A1;
wire net50;
wire B2;
wire A4;
wire B6;
wire S2;
wire Cin;
wire BH1;
wire net61;
wire A2;
wire nothing;
wire S1;
wire A5;
wire S0;
wire net54;
wire B0;
wire B4;
wire net58;

\1bit_FA     
 I6  ( .Cin( net61 ), .VDD( VDD ), .A( A5 ), .Cout( nothing ), .B( B6 ), .GND( GND ), .Sum( S5 ) );

\1bit_FA     
 I5  ( .Cin( net58 ), .VDD( VDD ), .A( A4 ), .Cout( net61 ), .B( B5 ), .GND( GND ), .Sum( S4 ) );

\1bit_FA     
 I4  ( .Cin( net54 ), .VDD( VDD ), .A( A3 ), .Cout( net58 ), .B( B4 ), .GND( GND ), .Sum( S3 ) );

\1bit_FA     
 I3  ( .Cin( net50 ), .VDD( VDD ), .A( A2 ), .Cout( net54 ), .B( B2 ), .GND( GND ), .Sum( S2 ) );

\1bit_FA     
 I1  ( .Cin( net47 ), .VDD( VDD ), .A( A1 ), .Cout( net50 ), .B( BH1 ), .GND( GND ), .Sum( S1 ) );

\1bit_FA     
 I0  ( .Cin( Cin ), .VDD( VDD ), .A( A0 ), .Cout( net47 ), .B( B0 ), .GND( GND ), .Sum( S0 ) );

endmodule

