// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module \12to1MUX  (
Selector,GND,Vdd,A0,A1,A2,A3,A4,A5,B0,B1,B2,B3,B4,B5,Out0,Out1,Out2,Out3,Out4,Out5 );
input  Selector;
input  GND;
input  Vdd;
input  A0;
input  A1;
input  A2;
input  A3;
input  A4;
input  A5;
input  B0;
input  B1;
input  B2;
input  B3;
input  B4;
input  B5;
output  Out0;
output  Out1;
output  Out2;
output  Out3;
output  Out4;
output  Out5;
wire B5;
wire Out4;
wire Vdd;
wire B1;
wire A1;
wire A0;
wire Out0;
wire Selector;
wire B0;
wire Out1;
wire Out3;
wire A2;
wire B4;
wire A4;
wire A5;
wire B2;
wire GND;
wire Out2;
wire A3;
wire Out5;
wire B3;

MUXblock    
 I5  ( .Vdd( Vdd ), .C( Selector ), .A( B5 ), .GND( GND ), .B( A5 ), .Out( Out5 ) );

MUXblock    
 I4  ( .Vdd( Vdd ), .C( Selector ), .A( B0 ), .GND( GND ), .B( A0 ), .Out( Out0 ) );

MUXblock    
 I3  ( .Vdd( Vdd ), .C( Selector ), .A( B1 ), .GND( GND ), .B( A1 ), .Out( Out1 ) );

MUXblock    
 I2  ( .Vdd( Vdd ), .C( Selector ), .A( B4 ), .GND( GND ), .B( A4 ), .Out( Out4 ) );

MUXblock    
 I1  ( .Vdd( Vdd ), .C( Selector ), .A( B3 ), .GND( GND ), .B( A3 ), .Out( Out3 ) );

MUXblock    
 I0  ( .Vdd( Vdd ), .C( Selector ), .A( B2 ), .GND( GND ), .B( A2 ), .Out( Out2 ) );

endmodule

