# CS 111 Lab4 part1
# Jaehyung Park
# 504212821

SOURCE_FILES = lab4a.c
OTHER_FILES = Makefile

build:
	gcc -lmraa -lm -lpthread -std=gnu99 lab4a.c -o lab4a

clean:
	rm lab4a

dist:
	tar -czvf lab4-504212821.tar.gz $(SOURCE_FILES) $(OTHER_FILES)


